server:
  port: 8888

# file system
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:C:\Users\USER\Documents\python_jong\LikeLion\week10\config-native-local

# git hub
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/{git address}
          clone-on-start: true
          basedir: .config-git-remote

  security:
    user:
      name: root
      password: jongking97