spring:
  profiles:
    active: local # -> 요기서 변경

#logging:
#  level:
#    root: debug -> 로그 기본 레벨 설정
#    com.jongking.jpa: info -> 패키지 내부에 있는 info만

---
# h2 실제 db 저장안하고 메모리상에서 운용 (test용)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect