spring:
  profiles:
    active: test

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, loggers, shutdown, prometheus
#management.endpoint.<function>.enabled=true
#management.endpoint.<function>.show-details=always
  endpoint:
    health:
      show-details: always
      show-components: always
